apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: unusual-mammal-go
  janus-idp.io/tekton: unusual-mammal-go
  backstage.io/kubernetes-id: unusual-mammal-go
  backstage.io/kubernetes-namespace: rhtap-integ 
  app.kubernetes.io/part-of: unusual-mammal-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
